# Generated by Django 3.2 on 2023-07-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_auto_20230706_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Items_Sold',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
