# Generated by Django 3.2 on 2023-07-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0003_paper_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='format',
            field=models.CharField(choices=[('Colored', 'Colored'), ('Black and White', 'Black and White')], max_length=100, null=True),
        ),
    ]
