# Generated by Django 3.2 on 2023-07-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0004_paper_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='format',
            field=models.CharField(choices=[('Colored', 'Colored'), ('Black and White', 'Black and White'), ('Any', 'Any')], max_length=100, null=True),
        ),
    ]
