# Generated by Django 4.2.7 on 2023-12-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0005_alter_paper_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='Size',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A2', 'A2'), ('A1', 'A1')], max_length=10, null=True),
        ),
    ]
