# Generated by Django 4.2.7 on 2023-12-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Largeformat', '0002_alter_roll_buying_price_alter_roll_meters_left_and_more'),
        ('Printing', '0002_remove_printing_printed_by'),
        ('Sales', '0002_remove_sale_selling_price'),
        ('Employees', '0002_employee_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='large_format_attribute',
            field=models.ManyToManyField(related_name='employee_largeprints', to='Largeformat.largeformatprinting'),
        ),
        migrations.AddField(
            model_name='employee',
            name='printing',
            field=models.ManyToManyField(to='Printing.printing'),
        ),
        migrations.AddField(
            model_name='employee',
            name='printing_attribute',
            field=models.ManyToManyField(related_name='employee_prints', to='Printing.printing'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sales_attribute',
            field=models.ManyToManyField(to='Sales.sale'),
        ),
    ]
