# Generated by Django 3.2 on 2023-07-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0008_branch_name'),
        ('Admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='current_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Branches.branch'),
        ),
    ]
