# Generated by Django 3.2 on 2023-07-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branches', '0001_initial'),
        ('Expenses', '0001_initial'),
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='Cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_cashier', to='Employees.employee'),
        ),
        migrations.AddField(
            model_name='branch',
            name='Employees',
            field=models.ManyToManyField(to='Employees.Employee'),
        ),
        migrations.AddField(
            model_name='branch',
            name='Expenses',
            field=models.ManyToManyField(to='Expenses.Expense'),
        ),
    ]
