# Generated by Django 3.2 on 2023-07-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reports', '0001_initial'),
        ('Branches', '0003_branch_printing'),
        ('Stock', '0001_initial'),
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='Reports',
            field=models.ManyToManyField(to='Reports.Report'),
        ),
        migrations.AddField(
            model_name='branch',
            name='Sales',
            field=models.ManyToManyField(to='Sales.Sale'),
        ),
        migrations.AddField(
            model_name='branch',
            name='Stock',
            field=models.ManyToManyField(to='Stock.Stock'),
        ),
    ]
