# Generated by Django 3.2 on 2023-07-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
        ('Employees', '0001_initial'),
        ('Branches', '0005_auto_20230706_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='Employees',
            field=models.ManyToManyField(blank=True, to='Employees.Employee'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='Expenses',
            field=models.ManyToManyField(blank=True, to='Expenses.Expense'),
        ),
    ]
