# Generated by Django 3.2 on 2023-07-06 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
        ('Branches', '0006_auto_20230706_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='Cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_cashier', to='Employees.employee'),
        ),
    ]
