# Generated by Django 3.2 on 2023-07-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0007_alter_branch_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
