# Generated by Django 3.2 on 2023-07-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Cash',
        ),
        migrations.AddField(
            model_name='report',
            name='Balance',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='Cash_Taken',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
