# Generated by Django 3.2 on 2023-07-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_auto_20230704_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Printing',
        ),
        migrations.AddField(
            model_name='report',
            name='Printing',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='report',
            name='Sales',
        ),
        migrations.AddField(
            model_name='report',
            name='Sales',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
