# Generated by Django 4.2.7 on 2023-12-15 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(choices=[('Magenta', 'Magenta'), ('Cyan', 'Cyan'), ('Yellow', 'Yellow'), ('Black', 'Black')], max_length=100)),
                ('Bottles_Available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Solid Sticker', 'Solid Sticker'), ('One-way Sticker', 'One-way Sticker'), ('Banner', 'Banner'), ('Panaflex', 'Panaflex')], max_length=100)),
                ('Buying_Price', models.IntegerField()),
                ('Price_per_sq_meter', models.IntegerField()),
                ('Rolls_Available', models.IntegerField()),
                ('Meters_Sold', models.FloatField()),
                ('Meters_Left', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LargeformatPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meters_Printed', models.FloatField()),
                ('AmountPaid', models.IntegerField()),
                ('Roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Largeformat.roll')),
            ],
        ),
    ]
