# Generated by Django 4.2.7 on 2023-12-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Largeformat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='Buying_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='Meters_Left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='Meters_Sold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
