# Generated by Django 4.2.7 on 2023-12-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Largeformat', '0003_remove_largeformatprinting_amountpaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='Width',
            field=models.FloatField(null=True),
        ),
    ]
