# Generated by Django 4.2.7 on 2023-12-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Largeformat', '0005_alter_largeformatprinting_total_meters_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='largeformatprinting',
            name='Amount_Expected',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
