# Generated by Django 3.2 on 2023-07-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=1000)),
                ('code', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmailConfimation',
        ),
    ]
