# Generated by Django 3.2 on 2023-07-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Printing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printing',
            name='Printed_By',
        ),
    ]
