# Generated by Django 3.2 on 2023-07-04 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Quantity', models.PositiveIntegerField()),
                ('Selling_Price', models.PositiveIntegerField()),
                ('Money_Collected', models.PositiveIntegerField()),
                ('Refunded', models.BooleanField(default=False)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
