# Generated by Django 4.2.7 on 2023-12-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_sale_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Money_Expected',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
