# Generated by Django 4.2.7 on 2023-12-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('Merchandise', 'Merchandise'), ('Paper', 'Paper')], max_length=100, null=True),
        ),
    ]
